bleachkw/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from student.views import StudentHome
from django.conf.urls.static import static  
from django.conf import settings



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',StudentHome.as_view(),name='student_home'),
    url(r'^student/',include('student.urls',namespace='student')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

student/urls.py
from django.conf.urls import url, include
from django.conf import settings

from student import views
 


 
urlpatterns=[

		url(r'^student_add/$',views.StudentAdd.as_view(),name='student_add'),
		url(r'^student_edit/(?P<student_id>\d+)$',views.StudentEdit.as_view(),name='student_edit'),
		url(r'^student_delete/(?P<student_id>\d+)$',views.StudentDelete.as_view(),name='student_delete'),

   ]

student/models.py
from django.db import models

# Create your models here.

student/forms.py
from django import forms
from user.models import UserProfile


class StudentRegisterForm(forms.ModelForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
      model = UserProfile
      fields = ('name','gender','mobile_no','email_adderss','photo','date_of_birth','blood_group','religion','mother_tongue','country','state','city','place_of_residence','pin','permanent_address','current_address','date_of_join','fathers_name','fathers_qualification','fathers_occupation','fathers_mobile','fathers_email','mothers_name','mothers_qualification','mothers_occupation','mothers_mobile','mothers_email','guardians_name','guardians_relation','guardians_mobile1','guardians_mobile2') 

    def __init__(self, *args, **kwargs):
        super(StudentRegisterForm, self).__init__(*args, **kwargs)

        self.fields['name'].required = True

student/views.py
from django.shortcuts import render,redirect
from django.views import View
from django.contrib import messages 
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from bleachkw.utils import get_error
import string    
import random
from django.db.models import Q
import functools
import operator

from user.models import UserProfile
from student.forms import StudentRegisterForm


#for unique order id
def random_string_generator(size=10, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))


def unique_username_generator():
    new_username = random_string_generator()

    username_exists    = UserProfile.objects.filter(username=new_username).exists()
    if username_exists:
        return unique_order_id_generator()
    return new_username


# Create your views here.

class StudentHome(View):
	def get(self,request):
		page 		= 	self.request.GET.get('page',1)
		
		try:
			students = UserProfile.objects.filter(is_active=True)
		except:
			students = None
        
		fil_query           = request.GET.get('search')	
		fil_byname          = request.GET.get('filter_name')
		
		#search filter
		if fil_query:
			students = students.filter(Q(Q(name__icontains=fil_query)))
		
		#ascending descending filter
		if fil_byname:
			if  fil_byname == 'ascending':
				students = students.order_by('name')
			elif fil_byname == 'descending':
				students = students.order_by('-name')	
			else:
				pass

		fil_gender          = request.GET.get('fil_gender')
		fil_bloodgroup      = request.GET.get('fil_bloodgroup')	

		#Student table other filters 
		filters=[] 
		if fil_gender: 
		    case1 = Q(gender=fil_gender)
		    filters.append(case1)
		if fil_bloodgroup:
		    case2 = Q(blood_group=fil_bloodgroup)
		    filters.append(case2)          

		if fil_gender or fil_bloodgroup: 
			filters=functools.reduce(operator.and_,filters)
			students=students.filter(filters)	

		paginator	=	Paginator(students,100)
		
		try:
			students	=	paginator.page(page)		
		except PageNotAnInteger:
			students	=	paginator.page(1)
		except EmptyPage:
			students 	= 	paginator.page(paginator.num_pages)
		
		index 		= 	students.number - 1
		max_index 	= 	len(paginator.page_range)
		start_index = 	index - 6 if index >= 6 else 0
		end_index 	= 	index + 6 if index <= max_index - 6 else max_index
		page_range 	= 	list(paginator.page_range)[start_index:end_index]

		return render(request,'student/student_list.html',{"page_range":page_range,"students":students,"fil_query":fil_query,"fil_bloodgroup":fil_bloodgroup,"fil_gender":fil_gender,"fil_byname":fil_byname,})

class StudentAdd(View):
	def get(self,request):

		student_reg_form = StudentRegisterForm()
		
		return render(request,'student/student_add.html',{"student_reg_form":student_reg_form})	

	def post(self,request):
		student_reg_form = StudentRegisterForm(request.POST,request.FILES or None)
		
		if student_reg_form.is_valid():
			student_reg_form_save          = student_reg_form.save(commit=False)
			student_reg_form_save.username = unique_username_generator()
			student_reg_form_save.user_type= 'STUDENT'
			student_reg_form_save.save()
		else:			
			messages.error(request,get_error(student_reg_form))			
			return render(request,'student/student_add.html',{"student_reg_form":student_reg_form})
		return redirect('student_home')	

class StudentEdit(View):
	def get(self,request,student_id):

		try:
			student = UserProfile.objects.get(id=student_id)
		except:
			student = None	

		student_edit_form = StudentRegisterForm(instance=student)
		
		return render(request,'student/student_edit.html',{"student_edit_form":student_edit_form})	

	def post(self,request,student_id):

		try:
			student = UserProfile.objects.get(id=student_id)
		except:
			student = None	

		student_edit_form = StudentRegisterForm(request.POST,request.FILES or None,instance=student)
		

		if student_edit_form.is_valid():
			student_edit_form_save          = student_edit_form.save(commit=False)
			student_edit_form_save.save()
		else:			
			messages.error(request,get_error(student_edit_form))			
			return render(request,'student/student_edit.html',{"student_edit_form":student_edit_form})
		return redirect('student_home')

class StudentDelete(View):
	def get(self,request,student_id):
		try:
			student_delete = UserProfile.objects.filter(id=student_id).update(is_active=False)
		except:
			student_delete = None
		
		if student_delete:
			messages.success(request,"Student Succesfully Deleted")
		else:
			messages.error(request,"An error occured !!!")

		return redirect('student_home')	

templates/student/student_add.html
{% extends "base.html" %}

{% block content %}

{% load static %}

<div class="product_add">

  {% include 'student/common/header.html' %}

  <div class="row page-head">

    <div class="col-md-6"> 

      <h1>Registration</h1>

    </div>

    <div class="col-md-6">       
    <a href="{% url 'student_home' %}">
      <button class="back-btn" type="button">Back</button>
     </a>
     </div>

  </div>

  <div class="row">

    <div class="col-12"> 

      <div class="page-form">

        <form method="post" action="" enctype= "multipart/form-data">{% csrf_token %}

         <div class="page-form-head">

           <h1>Student add</h1>

         </div>

         <div class="page-body">

          {% for field in student_reg_form %} 

          <div class="page-col">

           {{ field.errors }} 

           {{ field.label_tag }} {{ field }}

          <p class="help">{{ field.help_text|safe }}</p>

          </div>

          {% endfor %}

          </div> 

          </div>
            <input type="submit" value="Save">
        </form>
        
        </div>



    </div>

         </div>    

   </div>

  </div>

  </div>

</div>

<!-- /product_add -->

{% endblock %}

templates/student/student_edit.html
{% extends "base.html" %}

{% block content %}

{% load static %}

<div class="product_add">

  {% include 'student/common/header.html' %}

  <div class="row page-head">

    <div class="col-md-6"> 

      <h1>Edit Registration</h1>

    </div>

    <div class="col-md-6">       
    <a href="{% url 'student_home' %}">
      <button class="back-btn" type="button">Back</button>
     </a>
     </div>

  </div>

  <div class="row">

    <div class="col-12"> 

      <div class="page-form">

        <form method="post" action="" enctype= "multipart/form-data">{% csrf_token %}

         <div class="page-form-head">

           <h1>Student Edit</h1>

         </div>

         <div class="page-body">

          {% for field in student_edit_form %} 

          <div class="page-col">

           {{ field.errors }} 

           {{ field.label_tag }} {{ field }}

          <p class="help">{{ field.help_text|safe }}</p>

          </div>

          {% endfor %}

          </div> 

          </div>
            <input type="submit" value="Update">
        </form>
        
        </div>



    </div>

         </div>    

   </div>

  </div>

  </div>

</div>

<!-- /product_add -->

{% endblock %}

templates/student/student_list.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div class="students">
  {% include 'student/common/header.html' %}

  <div class="row page-head">
      
    <div class="col-md-3">  
      <h1>Students</h1> 
    </div>

    <div class="col-md-9"> 
    <!-- search -->
    <div class="search"> 
      <form>
          <input type="search" placeholder="search for" maxlength="100" value="{{fil_query|default_if_none:''}}" name="search"  id="fil_query" onchange ="set_params_go()" />
          <button type="button" class="fa fa-search" aria-hidden="true"></button>
      </form>
    </div>      
    <button type="button"><a href="{% url 'student:student_add' %}">Add Student</a></button>
    </div>
   </div>
   <div class="table-head print-hide"> 
     <div class="left">   
        <div class="table-head selects">
            <select id="fil_gender" name="gender" onchange="set_params_go({});"> 
               <option value="">Gender</option>  
               <option value="MALE" {% if fil_gender == "MALE" %}selected{%endif%}>Male</option>
               <option value="FEMALE" {% if fil_gender == "FEMALE" %}selected{%endif%}>Female</option>
           </select>
           <select id="fil_blood" style="width:150px;" name="bloodgroup" onchange="set_params_go({});">
               <option value="">Blood Group</option> 
       <option value="A Positive" {% if fil_bloodgroup == "A Positive" %}selected{%endif%}>A+</option>
       <option value="A Negative" {% if fil_bloodgroup == "A Negative" %}selected{%endif%}>A-</option>
       <option value="B Positive" {% if fil_bloodgroup == "B Positive" %}selected{%endif%}>B+</option>
       <option value="B Negative" {% if fil_bloodgroup == "B Negative" %}selected{%endif%}>B-</option>
       <option value="AB Positive" {% if fil_bloodgroup == "AB Positive" %}selected{%endif%}>AB+</option>
       <option value="AB Negative" {% if fil_bloodgroup == "AB Negative" %}selected{%endif%}>AB-</option>
       <option value="O Positive" {% if fil_bloodgroup == "O Positive" %}selected{%endif%}>O+</option>
       <option value="O Negative" {% if fil_bloodgroup == "O Negative" %}selected{%endif%}>O-</option>
              </select>
              <a class="a-btn text-btn" href="{% url 'student_home' %}">Reset</a>
        </div>
      </div>
   </div>          
 

<div class="row">
    <div class="col-12">
            <div class="table-responsive">
              <div class="common-table">
               <table class="table">
                  <thead>
                    <tr class="tr-head">
                      <th class="xs-tcol">Sl.No</th>
                      <th class="m-tcol">Name
                        {% if fil_byname == 'ascending' %}
                        <button onclick="FilterByNameDescending()"> 
                           <i id="ordering_tag" class="fa fa-sort-alpha-desc" aria-hidden="true"></i>
                        </button>
                        {% elif fil_byname == 'descending' %}
                        <button onclick="FilterByNameAscending()">
                         <i id="ordering_tag" class="fa fa-sort-alpha-asc" aria-hidden="true"></i>
                        </button>
                        {%else%} 
                        <button onclick="FilterByNameAscending()"> 
                        <i id="ordering_tag" class="fa fa-sort-alpha-asc" aria-hidden="true"></i>
                        </button>  
                        {%endif%}
                      </th>
                      <th class="xs-tcol">Gender</th>
                      <th class="xs-tcol">Photo</th>
                      <th class="m-tcol">Mobile No</th>
                      <th class="xs-tcol">Email</th>
                      <th class="xs-tcol">Dob</th>
                      <th class="xs-tcol">Religion</th>
                      <th class="xs-tcol">Blood Group</th>
                      <th class="xs-tcol">Mother Tongue</th>
                      <th class="btn-tcol">Edit</th>
                      <th class="btn-tcol">Delete</th>
                    </tr>
                  </thead>
                  <tbody>
                    {%for student in students%} 
                     <tr class="tr-body"> 
                       <td class="xs-tcol">{{forloop.counter0|add:students.start_index}}</td>
                       <td class="m-tcol">{{student.name}}</td>
                       <td class="xs-tcol">{{student.gender|default_if_none:''}}</td>
                       <td class="xs-tcol"> 
                        {% if student.photo %}
                         <img src="{{student.photo.url}}" />
                        {% endif%}
                       </td>
                       <td class="m-tcol">{{student.mobile_no|default_if_none:''}}</td>
                       <td class="xs-tcol">{{student.email_adderss|default_if_none:''}}</td>
                       <td class="xs-tcol">{{student.date_of_birth|default_if_none:''}}</td>
                       <td class="xs-tcol">{{student.religion|default_if_none:''}}</td>
                       <td class="xs-tcol">{{student.blood_group|default_if_none:''}}</td>
                       <td class="xs-tcol">{{student.mother_tongue|default_if_none:''}}</td>
                       <td class="btn-tcol">
                        <a class="a-btn" href="{% url 'student:student_edit' student.id %}">Edit</a>
                       </td>
                       <td class="btn-tcol">
                        <a class="a-btn" href="{% url 'student:student_delete' student.id %}" >Delete</a>
                       </td>
                     </tr>
                  {% endfor %}
                   </tbody>
                </table> 

               {% if students.has_other_pages %}
                <ul class="paginated">
                {% if students.has_previous %}
                 <li><a href="?page={{ students.previous_page_number }}&search={{fil_query}}&fil_gender={{request.GET.fil_gender}}&fil_bloodgroup={{request.GET.fil_bloodgroup}}">&laquo;</a></li>
                 {% else %}
                <li class="disabled"><a>&laquo;</a></li>
                 {% endif %}
                 {% for pg in page_range %}
                  {% if students.number == pg %}
                    <li><a href="?page={{pg}}&search={{fil_query}}&fil_gender={{request.GET.fil_gender}}&fil_bloodgroup={{request.GET.fil_bloodgroup}}">{{pg}}</a></li>
                   {% else %}
                    <li><a href="?page={{pg}}&search={{fil_query}}&fil_gender={{request.GET.fil_gender}}&fil_bloodgroup={{request.GET.fil_bloodgroup}}">{{pg}}</a></li>
                 {% endif %}
                 {% endfor %}
                {% if students.has_next %}
                <li><a href="?page={{ students.next_page_number }}&search={{fil_query}}&fil_gender={{request.GET.fil_gender}}&fil_bloodgroup={{request.GET.fil_bloodgroup}}">&raquo;</a></li>
                {% else %}
                <li class="disabled"><a>&raquo;</a></li>
                {% endif %}
              </ul>
              {% endif %}

              </div>
          </div>
    </div>
  </div>
      </div>

</div>
<!-- students -->
{% endblock %}
{% block javascript %} 
<script>   
function FilterByNameAscending() 
{
  set_params_go({'filter_name':'ascending'}); 
} 
function FilterByNameDescending()  
{
  set_params_go({'filter_name':'descending'}); 
}

  
function set_params_go(args)   
{
var url='{% url 'student_home' %}';
var params={fil_query:$('#fil_query').val(),fil_gender:$('#fil_gender').val(),fil_bloodgroup:$('#fil_blood').val(),
};
for(key in args)
  params[key]=args[key];
var query='';
for(key in params) 
  if(params[key])
    query+='&'+key+'='+params[key].toString();
query=query.replace('&','?');
console.log(query);
window.location.href=url+query
}
</script>

{% endblock %}